# GET http://localhost:3005/api/spreadsheet/work-shifts
# GET http://localhost:3005/api/spreadsheet/work-shift?type=workShift&email=rina.kobayashi@nihon-sales.com


# GET https://script.google.com/a/macros/nihon-sales.com/s/AKfycbziG8O1u1NAkyWYc4weRtge8if33ZGN3KbsCjQZQnvurY8GQYjCJcIJpnmwgB5BaLoatQ/exec?type=members&email=emi.ohashi@nihon-sales.com

# POST http://localhost:3005/api/spreadsheet/work-shifts
# Content-Type: application/json

# {
# 	"type": "workShift",
# 	"memberId": "RS-1000",
# 	"startDatetime": "2025-07-01T09:00:00.000Z",
# 	"endDatetime": "2025-07-01T18:00:00.000Z"
# }

# POST http://localhost:3005/api/spreadsheet/work-reports
# Content-Type: application/json

# {
# 	"type": "workReport",
# 	"memberId": "RS-1000",
# 	"startDatetime": "2025-07-01T09:00:00.000Z",
# 	"endDatetime": "2025-07-01T18:00:00.000Z",
# 	"restTime": 30,
# 	"absenceTime": 60,
# 	"workResult": "3\n1\n1",
# 	"highlightsAndReflections": "名前がわかっているところを探してかけたりしたこと\nリストのことなどもあり架電数がかなり少なかったので来週以降架電数もっとあげられるように頑張ります！",
# 	"tomorrowFocus": "関係構築・架電数・接続数",
# 	"feedbackRequestPhone": "090-1234-5678"
# }

# POST http://localhost:3005/api/spreadsheet/new-contract-employee
# Content-Type: application/json

# {
# 	"name": "山田太郎",
# 	"nameKana": "ヤマダタロウ",
# 	"personalAddress": "yama@gmail.com",
# 	"phoneNumber": "090-1234-5678",
# 	"bankName": "三菱UFJ銀行",
# 	"branchName": "本店",
# 	"accountType": "普通",
# 	"accountNumber": "1234567890",
# 	"accountHolder": "山田太郎",
# 	"birthday": "1990-01-01",
# 	"address": "東京都千代田区永田町1-7-1",
# 	"home": "東京都千代田区永田町1-7-1",
# 	"earliestStartDate": "2025/05/01",
# 	"estimatedWorkingHoursPerMonth": 160
# }

# POST http://localhost:3005/api/spreadsheet/joining-company
# Content-Type: application/json

# {
# 	"type": "newContractEmployee",
# 	"name": "山田太郎",
# 	"nameKana": "ヤマダ",
# 	"personalAddress": "sample@example.com",
# 	"phoneNumber": "080-1234-5678",
# 	"residenceAddress": "東京都渋谷区渋谷1-1-1",
# 	"currentAddress": "東京都渋谷区渋谷1-1-1",
# 	"nearestStation": "JR渋谷駅",
# 	"bankName": "〇〇銀行",
# 	"branchName": "〇〇支店",
# 	"accountType": "普通",
# 	"accountNumber": "1234567",
# 	"accountHolder": "ヤマダタロウ",
# 	"birthday": "2025-06-30",
# 	"joinDate": "2025-07-01",
# 	"myNumber": "1234567890122",
# 	"householdHead": "山田花子",
# 	"householdHeadRelationship": "本人",
# 	"emergencyContact": "080-1234-5678",
# 	"emergencyContactRelationship": "配偶者",
# 	"previousJobResignationDate": "2024-03-31",
# 	"employmentInsuranceNumber": "1234-567890-1"
# }